//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTOTAL_Quick_List_Copier.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickList
    {
        public QuickList()
        {
            this.QuickListEntries = new HashSet<QuickListEntry>();
        }
    
        public int QLID { get; set; }
        public int QLNameID { get; set; }
        public string FieldName { get; set; }
        public string FormType { get; set; }
        public int Number { get; set; }
        public string ShortName { get; set; }
        public System.DateTime DateEntered { get; set; }
        public bool ShowInAllView { get; set; }
    
        public virtual QuickListName QuickListName { get; set; }
        public virtual ICollection<QuickListEntry> QuickListEntries { get; set; }
    }
}
