//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTOTAL_Quick_List_Copier.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickListName
    {
        public QuickListName()
        {
            this.QuickLists = new HashSet<QuickList>();
        }
    
        public int QLNameID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<QuickList> QuickLists { get; set; }
    }
}
